### ISSUE TITLE
Single Session ghost controls

### ISSUE THREAD

**Issue by 89537kay3** [MrDaGree/ELS-FiveM#25]
**Describe the bug**
When entered into a single session, or purposefully leave the session for rockstar editor, ELS will randomly turn on lights and sirens as if someone else is controlling it.

**To Reproduce**
Single session whilst other people are in a normal session. Use ELS.

**Expected behavior**
No difference to usual use. 

**ELS Information:**
Version #: 1.75 (latest)
Server Version #: latest
Screenshots of Config.lua, vcf.lua, vcf folder: N/A (no additional files or edits)

**Additional context**

**Comment by JHodgson1** [comment]
+1 Can also reproduce. I had this issue when I was primarily using ELS-FiveM on my server. I forgot to make an issue at the time. I have a potential fix, I'll mess around with it and see if I can make a PR to fix this bug.

**Comment by 89537kay3** [comment]
Awesome! I’ll fiddle around and see what single session is being handled differently

**Comment by 89537kay3** [comment]
Any updates with this?

**Comment by Zeemahh** [comment]
> Any updates with this?

Not at that point. But a check for NetworkIsSessopnActive() should suffice.

**Comment by Zeemahh** [comment]
I've made a commit, to cover this (only a week late, oops). If you wish, you can download from the repo (not /releases) and set the convar `els_developer` to a truth-y value (1 or "true" - since booleans don't exist in convars) and provide feedback on this. You can forcefully put players in a split session by ending their network session, see [`NETWORK_SESSION_LEAVE_SINGLE_PLAYER`](https://runtime.fivem.net/doc/natives/#_0x3442775428FD2DAA).
