### ISSUE TITLE
Debug print seems to be broken at line 814

### ISSUE THREAD

**Issue by alex070609** [MrDaGree/ELS-FiveM#65]
Debugging return an impossible concatenation at line 814

https://imgur.com/a/oPUH7Pv

**Comment by MrDaGree** [comment]
Is your utils.lua up to date? It appears it cannot get vehicle model name from checkCarHash and thats causing the issue.

**Comment by alex070609** [comment]
yup, util.lua is up-to-date same version as your blob/master

**Comment by Zeemahh** [comment]
The error is definitely related to the debugPrint, but that shouldn't ever be called since the main issue that caused invalid index stuff was fixed.

Do you happen to be using OneSync Infinity?

**Comment by alex070609** [comment]
nope i'm using OneSync normla with 64 slots (patreon 15$)

**Comment by Zeemahh** [comment]
Very weird.

There's a `does_entity_exist` call which shouldn't be true in the case that the entity is nil, so this isn't the reasoning.

Only other reasoning is the `checkCarHash` function returning `nil` (or, not returning at all, since there is no default return value). I should just set the return value to `CARNOTFOUND`, for consistency with actual GTA natives. Though, I can't seem to figure out how to repro this, so, no fix, only a workaround.
